# Generated by Django 5.2.1 on 2025-06-03 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
